FROM touk/nussknacker:0.3.1-staging-2021-06-02-2333-dd5d4b4b8524e8e75e615b97d86aec675438e08f-SNAPSHOT
# TODO change and merge after 0.3.1 release

COPY opt/ /opt/

CMD ["/opt/nussknacker/bin/nussknacker-entrypoint.sh"]
