version: '3.8'

services:

  pmml-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/pmml/templates:/etc/nginx/templates
      - ./nginx/pmml/static:/etc/nginx/html
    ports:
      - "${PMML_SAMPLES_PORT}:${PMML_SAMPLES_PORT}"
      - "${PMML_NGINX_STATIC_PORT}:${PMML_NGINX_STATIC_PORT}"
    environment:
      - PMML_SAMPLES_PORT=${PMML_SAMPLES_PORT}
      - PMML_SAMPLES_URL=pmml-samples:${PMML_SERVER_PORT}
      - PMML_NGINX_STATIC_PORT=${PMML_NGINX_STATIC_PORT}
    networks:
      - pmml-net
      - dev-bridge-net

  pmml-samples:
    image: docker.pkg.github.com/prinz-nussknacker/prinz/pmml-samples:0.0.1
    environment:
      - PMML_SERVER_PORT=${PMML_SERVER_PORT}
    volumes:
      - ./pmml-samples/:/home/pmml
    networks:
      - pmml-net

networks:
  pmml-net:
    driver: bridge
  dev-bridge-net:
    driver: bridge
    external: true
