name: Release new version
on:
  push:
    branches: ['*']
    tags: [v*]
jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./sbtwrapper prinz/publish &&
          ./sbtwrapper prinz_mlflow/publish &&
          ./sbtwrapper prinz_pmml/publish

  release-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Prinz ${{ github.ref }}
          draft: false
          prerelease: false
